module.exports = {
  apps: [
    {
      name: 'emas-web',
      script: 'apps/web/.next/standalone/apps/web/server.js',
      cwd: '/home/ecetak/webapps/dev-emas',
      instances: 1,
      env: {
        NODE_ENV: 'production',
        PORT: '8000',
        HOSTNAME: '127.0.0.1',
        NEXT_PUBLIC_API_URL: 'https://dev.emas.my/api',
        NEXT_PUBLIC_SYSTEM_MAINTENANCE_MODE: 'off',
        NEXT_PUBLIC_SYSTEM_LOGIN: 'on',
        LOCAL_AI_BASE_URL: 'http://127.0.0.1:11434',
        LOCAL_AI_MODEL: 'qwen2.5:7b',
        LOCAL_AI_TIMEOUT_MS: '20000',
        DATABASE_URL: 'mysql://grouprint:12092k@localhost:3306/emas_db',
        REDIS_URL: 'redis://localhost:6379',
      },
      log_file: '/home/ecetak/logs/dev-emas-web.log',
      error_file: '/home/ecetak/logs/dev-emas-web-err.log',
      restart_delay: 3000,
      max_restarts: 5,
    },
    {
      name: 'emas-api',
      script: 'apps/api/dist/main.js',
      cwd: '/home/ecetak/webapps/dev-emas',
      instances: 1,
      env: {
        NODE_ENV: 'production',
        PORT: '8001',
        SYSTEM_MAINTENANCE_MODE: 'off',
        SYSTEM_LOGIN: 'on',
        SYSTEM_OWNER_EMAILS: 'admin@emas.my',
        DATABASE_URL: 'mysql://grouprint:12092k@localhost:3306/emas_db',
        REDIS_URL: 'redis://localhost:6379',
        JWT_SECRET: 'dev-emas-jwt-secret-must-be-32chars-min',
        JWT_EXPIRES_IN: '15m',
        JWT_REFRESH_EXPIRES_IN: '7d',
        ALLOWED_ORIGINS: 'https://dev.emas.my',
        LOCAL_AI_BASE_URL: 'http://127.0.0.1:11434',
        LOCAL_AI_MODEL: 'qwen2.5:7b',
        LOCAL_AI_TIMEOUT_MS: '12000',
      },
      log_file: '/home/ecetak/logs/dev-emas-api.log',
      error_file: '/home/ecetak/logs/dev-emas-api-err.log',
      restart_delay: 3000,
      max_restarts: 5,
    },
    {
      name: 'emas-worker',
      script: 'apps/worker/dist/main.js',
      cwd: '/home/ecetak/webapps/dev-emas',
      instances: 1,
      env: {
        NODE_ENV: 'production',
        DATABASE_URL: 'mysql://grouprint:12092k@localhost:3306/emas_db',
        REDIS_URL: 'redis://localhost:6379',
      },
      log_file: '/home/ecetak/logs/dev-emas-worker.log',
      error_file: '/home/ecetak/logs/dev-emas-worker-err.log',
      restart_delay: 3000,
      max_restarts: 5,
    },
  ],
}
